namespace Jackass.Backend.Models
{
    public enum LandmarkType
    {
        EyeLeft,
        RightPupil,
        RightEyeUp,
        RightEyeRight,
        RightEyeLeft,
        RightEyeDown,
        RightEyeBrowUp,
        RightEyeBrowRight,
        RightEyeBrowLeft,
        NoseRight,
        NoseLeft,
        Nose,
        MouthUp,
        MouthLeft,
        MouthDown,
        LeftPupil,
        LeftEyeUp,
        LeftEyeRight,
        LeftEyeLeft,
        LeftEyeDown,
        LeftEyeBrowUp,
        LeftEyeBrowRight,
        LeftEyeBrowLeft,
        EyeRight,
        MouthRight,
    }
}